apiVersion: v1
kind: Service
metadata:
  labels:
    run: assets
  name: assets
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    run: assets
status:
  loadBalancer: {}
