apiVersion: v1
kind: Service
metadata:
  labels:
    run: front-end
  name: front-end
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    run: front-end
  type: LoadBalancer
status:
  loadBalancer: {}
