apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: newsfeed
  name: newsfeed
spec:
  replicas: 1
  selector:
    matchLabels:
      run: newsfeed
  strategy: {}
  template:
    metadata:
      labels:
        run: newsfeed
    spec:
      containers:
        - args:
            - java
            - -jar
            - ./build/newsfeed.jar
          env:
            - name: APP_PORT
              value: "2000"
          image: image
          name: newsfeed
          ports:
            - containerPort: 2000
          resources: {}
      restartPolicy: Always
status: {}
