apiVersion: v1
kind: Service
metadata:
  labels:
    run: newsfeed
  name: newsfeed
spec:
  ports:
    - name: "2000"
      port: 2000
      targetPort: 2000
  selector:
    run: newsfeed
status:
  loadBalancer: {}
