apiVersion: v1
kind: Service
metadata:
  labels:
    run: quotes
  name: quotes
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    run: quotes
status:
  loadBalancer: {}
